### PR TITLE
Sudeep banjara

### PR DESCRIPTION
**Pull request by SudeepBanjara**
I made changes on the method and variables please check.

### CODE REVIEW

**Comment by SudeepBanjara** [comment]
hello fahim can you plese send the file to reviewer zeeshan

**Comment by SudeepBanjara** [comment]
i made changes on the file BorrowBookUi. java please check

**Comment by SudeepBanjara** [comment]
check all 4 files as i have finish the changes

**Comment by faheem735** [comment]
Done

**Pull request merged**
